### ISSUE TITLE
Search by complex values

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#1366]
@mansu raised a request on gitter to search by arbitrarily complex values (i.e. ones that have equals tokens in them)

> @mansu 05:05
> I think the problem is more subtler here: for example I can search for X-Real-Ip=66.87.120.xx, but X-Pinterest-Referrer=https://mail.google.com/mail/mu/mp/608/?source=nap&hr=1&hl=en-US doesn't work. Can it be that special characters are causing issues?

Realistically speaking, such a search isn't a great example as full urls aren't likely to work well with exact matching. that's why we call out which keys are good for filtering, vs others which are just context https://github.com/openzipkin/zipkin-api/blob/master/thrift/zipkinCore.thrift#L128

I suspect that equals characters interfere with the parser, as equals is a token in the encoding of a search expression

``` yaml
        - name: annotationQuery
          in: query
          type: string
          required: false
          description: |
             Ex. `http.uri=/foo and retried` - If key/value (has an `=`),
             constrains against Span.binaryAnnotations of time string. If just
             a word, constrains against Span.annotations. Any values are AND
             against eachother. This means a span in the trace must match all of
             these
```

Suman mentioned that the unpacking of the search expression could be at fault, for example it could look for the first = vs any of them. This might work, but needs to be tested well.
