### ISSUE TITLE
Allow customization of UI base tag for running behind proxies

### ISSUE THREAD

**Issue by stepanv** [openzipkin/zipkin#1731]
This is about introducing `ZIPKIN_UI_BASEPATH` so that proxies can naturally serve the correct base path for zipkin UI static content.

Original desc below. If more is needed follow-up issue should be raised.
---
It would be neat if Zipkin didn't enforce `/zipkin/` absolute path for the UI, but was able to run in variable context root such as `/api/v1/namespaces/default/services/zipkin-service/proxy/zipkin/` (Kubernetes apiserver proxy feature).

This is related to #1627 but it doesn't enforce the `zipkin` folder to be in a _root_.

I'm submitting a pull request.

**Comment by eirslett** [comment]
Unfortunately this is more complicated than you would think, because of the web UI is a single page webapp, and that comes with some limitations. We chose to hardcode it to /zipkin/ as a compromise between usability and code complexity.

**Comment by stepanv** [comment]
You're right it adds complexity. As you can see from the linked merge request, `/` (as a root) has to be substituted with the _context path_ where absolute paths are used.

Maybe it would be worth replacing the `__webpack_public_path__` with something else but in general I think the idea itself doesn't result with too complex code. Let me know what you think.

**Comment by wdittmer** [comment]
Was typing the stuff below and then found it was probably the same as this issue.
Below are my findings, which might help someone else to see if there can be done something to make this work.

This issue is related to the work already done for #1229 and #1627 .
What we are trying to do is the following:
We have build up a Kubernetes cluster where we run the openzipkin/zipkin service and an ingress controller to reach various services like Kibana, Grafana, ElasticSearch and also zipkin.

The ingress controller looks a follows:
```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cbo-ingress-mgmt-elb
  namespace: monitoring
  labels:
    app: ingressservice-mgmt-elb
    dns: route53
  annotations:
    # kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/rewrite-target: /
    ingress.kubernetes.io/ssl-redirect: "false"
    domainName: "mgmt.$DOMAIN"
spec:
  rules:
  - host: management.${CNF_ENV}.cbo
    http:
      paths:
      - backend:
          serviceName: alertmanager
          servicePort: 9093
        path: /alertmanager
      - backend:
          serviceName: elasticsearch
          servicePort: 9200
        path: /elasticsearch
      - backend:
          serviceName: grafana
          servicePort: 3000
        path: /grafana
      - backend:
          serviceName: kibana
          servicePort: 5601
        path: /kibana
      - backend:
          serviceName: prometheus-monitoring
          servicePort: 9090
        path: /prometheus
      - backend:
          serviceName: zipkin-service
          servicePort: 9411
        path: /zipkin
```
So for example, the Kibana service is now reachable via: http://management.test.cbo/kibana.
Kibana will then forward the browser to http://management.test.cbo/kibana/app/kibana
Kibana is configured with a SERVER_BASEPATH environment variable with value: "/kibana" and that works.

If we now go to http://management.test.cbo/zipkin then zipkin will forward the browser to http://management.test.cbo/zipkin/zipkin/ and you get a broken UI with the page only showing two links.
```html

<!DOCTYPE html>
--
  | <html>
  | <head>
  | <!--
  | add 'base' tag to work around the fact that 'html-webpack-plugin' does not work
  | with '__webpack_public_path__' being set as reported at https://github.com/jantimon/html-webpack-plugin/issues/119
  | -->
  | <base href="/zipkin/">
  |  
  | <link rel="icon" type="image/x-icon" href="favicon.ico">
  |  
  | <meta charset="UTF-8">
  | <title>Webpack App</title>
  | <link href="app-50c2a6865887222f5166.min.css" rel="stylesheet"></head>
  | <body>
  |  
  | <!-- we include a reduced header on page load, as this makes the page load feel much smoother -->
  |  
  | <div class='navbar navbar-inverse' role='navigation'>
  | <div class='container'>
  | <div class='navbar-header'>
  | <a class='navbar-brand' href='#'>
  | Zipkin<span class='muted' style='font-size: .75em; padding-left: 10px;' data-i18n="nav.inves">Investigate system behavior</span>
  | </a>
  | </div>
  | </div><!--/.nav-collapse -->
  | </div>
  | </div>
  |  
  | <script type="text/javascript" src="app-50c2a6865887222f5166.min.js"></script></body>
  | </html>
```

When we look at the generated nginx.conf from the ingress controller, we find that `ingress.kubernetes.io/rewrite-target: /` adds the following two redirects:
```
rewrite /zipkin/(.*) /$1 break;
rewrite /zipkin / break;
proxy_pass http://monitoring-zipkin-service-9411;
```

We created a simple nginx docker container:
```Docker
FROM nginx:latest

COPY nginx.conf /etc/nginx/nginx.conf
```

And the nginx.conf:
```
worker_processes 1;

events { worker_connections 1024; }


http {

    log_format compression '$remote_addr - $remote_user [$time_local] '
        '"$request" $status $upstream_addr '
        '"$http_referer" "$http_user_agent" "$gzip_ratio"';

    server {
        listen 8080;
        server_name reverse-proxy;
        access_log /var/log/nginx/access.log compression;

        location /zipkin {
            proxy_pass          http://docker.for.mac.localhost:32786;
            proxy_set_header    Host             $host;
            proxy_set_header    X-Real-IP        $remote_addr;
            proxy_set_header    X-Forwarded-For  $proxy_add_x_forwarded_for;
            proxy_read_timeout 1800;
            proxy_connect_timeout 1800;
        }
    }
}
```
Where port 32768 is mapped on the openzipkin/zipkin container 9411 port. The /etc/hosts file contains 
```
127.0.0.1 reverse-proxy
127.0.0.1 zipkin-server
```

If we go to http://reverse-proxy:8080/zipkin then the UI works.
If we now add the two extra rewrite rules, the UI breaks by going to /zipkin/zipkin/
I tried setting the SERVER_CONTEXT_PATH but that didn't do anything.

So this narrows it down to the ingress.kubernetes.io/rewrite-target: / setting, which does not work for zipkin. Since we have many services in the same namespace and domain, we are going to see if we can move zipkin out to its own configuration section where we can set the rewrite-target to /zipkin and see if that works.
