### ISSUE TITLE
404 Not found /app-...-min.js and /app-...-min.css

### ISSUE THREAD

**Issue by felodel** [openzipkin/zipkin#2153]
Hello,

I deployed zipkin on kubernetes but when i try to access to zipkin, it not found:

- app-6a05bdd92a449a6ee72a.min.css
- app-6a05bdd92a449a6ee72a.min.js

https://hostname/zipkin/app-6a05bdd92a449a6ee72a.min.js
timestamp | 2018-08-01T09:31:28.410+0000
-- | --
status | 404
error | Not Found
message | Not Found
path | /app-6a05bdd92a449a6ee72a.min.js

https://hostname/zipkin/app-6a05bdd92a449a6ee72a.min.css
timestamp | 2018-08-01T09:31:28.410+0000
-- | --
status | 404
error | Not Found
message | Not Found
path | /app-6a05bdd92a449a6ee72a.min.css

https://hostname/zipkin/zipkin/config.json
environment | ""
queryLimit | 10
defaultLookback | 3600000
instrumented | ".*"
logsUrl | null
basepath | "/zipkin"
searchEnabled | true
dependency |  
lowErrorRate | 0.5
highErrorRate | 0.75

my k8s ingress:
      {
              "path": "/zipkin",
              "backend": {
                "serviceName": "zipkin-service",
                "servicePort": 9411
              }
            },

In local with docker, It runs correctly.

Thank you for your time.

**Comment by codefromthecrypt** [comment]
does this help you?
https://github.com/openzipkin/zipkin/issues/1930#issuecomment-373335942

**Comment by felodel** [comment]
Hello Adrian,

Thank you for your help.

I have already tried:

         - name: ZIPKIN_UI_BASEPATH
           value: "/zipkin/zipkin

I check that the env parameter is set. I check it in /zipkin/env : 

ZIPKIN_UI_BASEPATH | "/zipkin/zipkin"

Nevertheless, zipkin don´t work.

I find a workaround to solve it:  https://github.com/knikitin/zipkin/commit/6330e767167669e35ad38e3fd7adffab00100d15

Using that docker image: knikitin/zipkin-service

But, that docker image is old (two years ago) and when I try to regiter my application in zipkin with:

spring.zipkin.baseUrl= http://zipkin-service:9411
spring.sleuth.sampler.percentage= 0.2

My application don´t connect with zipkin.

I only want a zipkin in memory storage.

Any solution ?

Thank you for your time. :)

**Comment by codefromthecrypt** [comment]
@zeagord do you have any hints or kubernetes deployment advice for this?

**Comment by felodel** [comment]
Adrian,

Do you now how I can generate a new image from https://github.com/openzipkin/zipkin where I modify zipkin-ui/js files?

like this commit: https://github.com/knikitin/zipkin/commit/6330e767167669e35ad38e3fd7adffab00100d15

My problem is that there are zipkin-ui and zipkin-server with each poms, so I want a docker image with those changes and las version zipkin.

is It possible? do you have a dockerfile to generate a image?

**Comment by codefromthecrypt** [comment]
firstly, that is indeed an old change.

Next, this is a relative URL
https://github.com/openzipkin/zipkin/blob/master/zipkin-ui/js/component_data/default.js#L49

I do believe there is something wrong with your setup if relative links
aren't resolving properly.

**Comment by zeagord** [comment]
Can you try set the base path to` / `? I'm using like the below one in the latest zipkin version and found no problems.

```
{
  "path": "/",
  "backend": {
  "serviceName": "zipkin-service",
  "servicePort": 9411
}
```

**Comment by felodel** [comment]
Helli @zeagord 

I tried that solution:

            {
              "path": "/zipkin",
              "backend": {
                "serviceName": "zipkin-service",
                "servicePort": 9411
              }
            }

But, it doesn´t work.

I only solve with https://github.com/knikitin/zipkin/commit/6330e767167669e35ad38e3fd7adffab00100d15

But my application doesn´t connect with zipkin.

So I want to create a new zipkin-ui docker image with relative url changes, but:

- Do you know how can I create a one docker image with zipkin-server and zipkin-ui?
or
- Do you know how I can create two dokcer images (zipkin-server and zipkin-ui) and to run each other ?
 
That are my service and deployment on k8s:

apiVersion: v1
kind: Service
metadata:
  name: zipkin-service
spec:
  ports:
  - port: 9411
    targetPort: 9411
    name: http
  selector:
    app: zipkin
  type: NodePort

---

#Deployment
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: zipkin-deployment
spec:
  selector:
    matchLabels:
      app: zipkin
  replicas: 1 # tells deployment to run 2 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin:2.10.4
        imagePullPolicy: Always
        env:
         - name: ZIPKIN_UI_BASEPATH
           value: "/zipkin/zipkin"

**Comment by felodel** [comment]
any solution ?
could you tell me how I can generate my own image zipkin from: https://github.com/openzipkin/zipkin?

I could change code as https://github.com/knikitin/zipkin/commit/6330e767167669e35ad38e3fd7adffab00100d15 and to make a new image.

Or also I have thought that I could modify zipkin-server-shared.yml (base-path param), to set base-path: /zipkin/zipkin and  remake a image.

What do you think about that?

Thank you for your time.

**Comment by zeagord** [comment]
Small tip. Wrap the deployment script with ```. So that it will be readable.

Try the below deployment script. I assume you're using Minkube. If that's true. Enable the ingress by `minikube addons enable ingress`. If not you have choose a ingress controller.

```
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: zipkin-service
spec:
  ports:
    - port: 9411
  selector:
    app: zipkin

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: zipkin
spec:
  replicas: 2
  selector:
    matchLabels:
      app: zipkin
  template:
    metadata:
      labels:
        app: zipkin
    spec:
      containers:
      - name: zipkin
        image: openzipkin/zipkin
      readinessProbe:
        httpGet:
        path: "/actuator/health"
        port: 9411
        initialDelaySeconds: 5
        
---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: zipkin-ingress
  annotations:
    kubernetes.io/ingress.allow-http: "true"
spec:
  backend:
    serviceName: zipkin-service
    servicePort: 9411

```
