### ISSUE TITLE
Cannot save dependencies data to table:'zipkin_dependecies'  when storage type is mysql

### ISSUE THREAD

**Issue by Chen1997c** [openzipkin/zipkin#2207]
I consider using mysql to save trace data, but the table 'zipkin_dependecies' lost data.‘zipkin_annotations’ and 'zipkin_spans' are quite normal.

**SpringBoot Version:1.5.8.RELESE 
SpringCloud Version:Dalston.SR1 
Zipkin version:1.23.2**
### **zipkin servers pom file:**

        
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin-autoconfigure-ui</artifactId>
        </dependency>

        
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-sleuth-zipkin-stream</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-stream-rabbit</artifactId>
        </dependency>

        
        <dependency>
            <groupId>io.zipkin.java</groupId>
            <artifactId>zipkin-autoconfigure-storage-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-jdbc</artifactId>
        </dependency>
        <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
        </dependency>

application.yml

```
server:
  port: 9411
eureka:
  client:
    service-url:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:9761}/eureka/
spring:
  datasource:
    schema: classpath:/mysql.sql
    url: jdbc:mysql:///party_building?useSSL=false
    username: root
    password: 19970914
    initialize: true
    continue-on-error: true
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  application:
    name: zipkin-server
  sleuth:
    enabled: false
    sampler:
      percentage: 1.0
zipkin:
  storage:
    type: mysql
```
emmm....It's my configuration's wrong, or zipkin's bug?
Thanks!
