### ISSUE TITLE
zipkin ui refresh request again response no anything

### ISSUE THREAD

**Issue by weixsun** [openzipkin/zipkin#2443]
docker-zipkin version:2.12.5

docker-zipkin version : 2.11.12 is ok. other version not test

deploy env: kubernetes v1.13.1

simple deploy yaml:
```yaml
env:
            - name: "STORAGE_TYPE"
              value: "elasticsearch"
            - name: "ES_HOSTS"
              value: "http://192.168.66.62:9200"
            - name: "ES_MAX_REQUESTS"
              value: "64"
            - name: "ES_INDEX"
              value: "rdc_cloud_zipkin_trace"
            - name: "ElasticsearchStorage.Builder.index"
              value: "rdc_cloud_zipkin_trace"
            - name: "ES_DATE_SEPARATOR"
              value: "."
            - name: "ElasticsearchStorage.Builder.dateSeparator"
              value: "."
            - name: "ES_INDEX_SHARDS"
              value: "5"
            - name: "ES_INDEX_REPLICAS"
              value: "1"
            - name: "KAFKA_BOOTSTRAP_SERVERS"
              value: "192.168.67.21:9092,192.168.67.22:9092,192.168.67.23:9092"
            - name: "KAFKA_TOPIC"
              value: "rdc_cloud_zipkin_trace"
            - name: "KAFKA_GROUP_ID"
              value: "rdc_cloud_zipkin_trace_zipkin_group"
            - name: "QUERY_PORT"
              value: "9411"
            - name: "ZIPKIN_UI_DEPENDENCY_LOW_ERROR_RATE"
              value: "0.3"
            - name: "ZIPKIN_UI_DEPENDENCY_HIGH_ERROR_RATE"
              value: "0.75"
            - name: "ZIPKIN_UI_LOGS_URL"
              value: "http://devcloud.i139.cn/kibana/app/kibana#/discover?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-7d,mode:quick,to:now))&_a=(columns:!(_source),index:'b7e371c0-4638-11e9-bad2-61d86dd48551',interval:auto,query:(language:lucene,query:'{traceId}'),sort:!(timestamp_millis,desc))"
            - name: "JAVA_OPTS"
              value: "-Xms1G -Xmx1G -Dlogging.level.zipkin=WARN -Dlogging.level.zipkin2=WARN"
```

First request zipkin ui every thing is OK.

![1111552621436_ pic_hd](https://user-images.githubusercontent.com/29357333/54407146-a3d55d80-4717-11e9-990c-e16d7d1b6415.jpg)

But when refresh zipkin ui in chrome browser, chrome browser print no thing,however the response is 200, And use curl http://zipkin-ui-url:9411 response normal data forever:

![1121552621504_ pic_hd](https://user-images.githubusercontent.com/29357333/54407188-cf584800-4717-11e9-8f34-2a4ec218cf89.jpg)

![1101552621381_ pic_hd](https://user-images.githubusercontent.com/29357333/54407101-82747180-4717-11e9-97ae-f6d24f8b09fe.jpg)
