### ISSUE TITLE
Zipkin server unable to consume span events from kafka transport

### ISSUE THREAD

**Issue by aniketvsawant** [openzipkin/zipkin#2478]
Hi Team,

Services are able to publish span messages to kafka using spring cloud sleuth but zipkin server is not able to consume the messages from kafka. Here is my details.

dependencies
```
  compile "io.zipkin.java:zipkin-server:2.12.5"
  compile "io.zipkin.java:zipkin-autoconfigure-ui:2.12.6"
  compile "org.springframework.cloud:spring-cloud-starter-stream-kafka:2.1.0.RELEASE"
``` 

ApplicationClass
```
@SpringBootApplication
@EnableZipkinServer
public class ZipkinServiceApplication {
    @Bean
    ServletWebServerFactory servletWebServerFactory(){
        return new TomcatServletWebServerFactory();
    }

    public static void main( String[] args ) {
        SpringApplication.run(ZipkinServiceApplication.class, args);
    }
}
```

application.properties
```
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          zkNodes: localhost:2181
```
Am i missing anything ? Zipkin is not able to consume messages from kafka and store it into the in-memory span store. So tracing is not showing on zipkin ui.

**Comment by devinsba** [comment]
A couple things:

1. Is there a reason you can't run the server that we release as an executable jar and docker container? Our release includes kafka support built in https://github.com/openzipkin/zipkin/tree/master/zipkin-server#zipkin-server
2. `@EnableZipkinServer` is deprecated and our small community is not able to provide support for building custom servers

If after trying our server releases you still have problems please reach out to us in our support room: https://gitter.im/openzipkin/zipkin or on our users mailing list: users@zipkin.incubator.apache.org

**Comment by aniketvsawant** [comment]
@devinsba Even i tried with zipkin kafka collector but still having same issue. I am running zipkin server as a spring boot fatjar.

FYI : Same thing is working over Web transport. But stopped working when changed to Kafka.

dependencies
```
  compile "io.zipkin.java:zipkin-server:2.12.5"
  compile "io.zipkin.java:zipkin-autoconfigure-ui:2.12.6"
  compile "io.zipkin.java:zipkin-autoconfigure-collector-kafka:2.12.6"
```

application.properties
```
zipkin:
  collector:
    kafka:
      bootstrap-servers: localhost:9092
      topic: zipkin
      group-id: zipkin
      streams: 1
```
