### ISSUE TITLE
Support unverified Elasticsearch SSL connections

### ISSUE THREAD

**Issue by AbdessamadHALLAL** [openzipkin/zipkin#3079]
Hello,
I want to link zipkin with kafka as collector and elasticsearch as storage.
I deployed zipkin on kubenetes and used the last image
```image: 'openzipkin / zipkin: latest'```
here is the deployment file:
```
spec: 
  containers: 
    - name: zipkin
      image: 'openzipkin/zipkin:latest'
      ports:
        - containerPort: 9411
          protocol: TCP
      env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: '192.14.20.1:9091'
        - name: STORAGE_TYPE
          value: elasticsearch
        - name: ES_HOSTS
          value: 'https://elastic.k8s-cloud.com:443'
        - name: ES_INDEX
          value: zipkin-distributed-tracing
        - name: ES_USERNAME
          value: elasicUser
        - name: ES_PASSWORD
          value: elasicPass
```

Kafka collector works well without problem but elastisearch does not work

here is zipkin's health:

```
{
  "status": "DOWN",
  "zipkin": {
    "status": "DOWN",
    "details": {
      "ElasticsearchStorage{initialEndpoints=https://elastic.k8s-cloud.com:443, index=zipkin-distributed-tracing}": {
        "status": "DOWN",
        "details": {
          "error": "java.lang.IllegalStateException: couldn't connect any of [Endpoint{elastic.k8s-cloud.com:443, ipAddr=192.14.20.2, weight=1000}]"
        }
      },
      "KafkaCollector{bootstrapServers=192.14.20.1:9091, topic=zipkin}": {
        "status": "UP"
      }
    }
  }
}
```

Do I have to modify the variables, knowing that the elastisearch host uses self-signed SSL?
Is there a way to disable SSL validation?

Thank you
