### ISSUE TITLE
secure connection to kafka fails with java.lang.ClassNotFoundException: org.ietf.jgss.GSSException

### ISSUE THREAD

**Issue by msillence** [openzipkin/zipkin#3426]
## Describe the Bug
I'm trying to collect stats from kafka in clonfluent cloud using SASL_SSL and the docker image
I have the following kubernetes config:

```
          command: ["java"]
          args: 
           - "-Xms128m"
           - "-Xmx1028m"
           - "-XX:+ExitOnOutOfMemoryError"
           - "-cp"
           - ".:BOOT-INF/lib/*"
           - "-Dlog4j2.disable.jmx=true"
           - "-Dlogging.level.zipkin2=DEBUG"
           - '-Dzipkin.collector.kafka.overrides.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="xxx" password="xxx";'
           - "-Dzipkin.collector.kafka.overrides.security.protocol=SASL_SSL"
           - "-Dzipkin.collector.kafka.overrides.sasl.mechanism=PLAIN"
           - "org.springframework.boot.loader.PropertiesLauncher"
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "pkc-l6wr6.europe-west2.gcp.confluent.cloud:9092"
            - name: KAFKA_TOPIC
              value: "zipkin"
            - name: COLLECTOR_KAFKA_ENABLED
              value: "true"
```

much as on gitter https://gitter.im/openzipkin/zipkin?at=602d767cdc108172e782bf76

## Steps to Reproduce
Start docker image with any SASL protocol 

## Expected Behaviour
I expect the consumer to connect and collect stats

## Actual Behaviour

The following stack trace

```
zipkin-74b76bfbd-dpz45 ksqldb2 org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:823) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:626) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:69) ~[zipkin-collector-kafka-2.23.16.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:265) ~[zipkin-collector-kafka-2.23.16.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at java.lang.Thread.run(Unknown Source) [?:?]
zipkin-74b76bfbd-dpz45 ksqldb2 Caused by: java.lang.NoClassDefFoundError: org/ietf/jgss/GSSException
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:171) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:737) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  ... 8 more
zipkin-74b76bfbd-dpz45 ksqldb2 Caused by: java.lang.ClassNotFoundException: org.ietf.jgss.GSSException
zipkin-74b76bfbd-dpz45 ksqldb2  at jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source) ~[?:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source) ~[?:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:171) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:737) ~[kafka-clients-2.8.1.jar:?]
zipkin-74b76bfbd-dpz45 ksqldb2  ... 8 more
```

**Comment by jcchavezs** [comment]
Ping @jeqo

**Comment by jeqo** [comment]
Hi there, my guess is that as `sasl.jaas.config` contains spaces, the Java process is not loaded properly. Similar to https://stackoverflow.com/questions/18358660/passing-system-properties-that-contains-spaces-to-tomcat-through-java-opts

Could you give a try loading properties from a file instead?

**Comment by sivern** [comment]
I have the same problem.
I tried to use the following command to start the jar package successfully, but the same configuration throws an exception when started in the docker environment
`java  -jar 'C:\Users\guoxiwen\Desktop\app.jar'  
         --logging.level.zipkin2=DEBUG 
         --zipkin.collector.kafka.enabled=true 
         --zipkin.collector.kafka.bootstrap-servers=SASL_PLAINTE
XT://10.57.0.136:9092,SASL_PLAINTEXT://10.57.0.137:9092,SASL_PLAINTEXT://10.57.0.138:9092 
--logging.level.org.apache.kafka=debug --zipkin.collector.kafka.overrides.security.protocol=SASL_PLAINTEXT 
--zipkin.collector.kafka.overrides.sasl.mechanism=PLAIN '
--zipkin.collector.kafka.overrides.sasl.jaas.config="org.apache.kafka.common.security.plain.PlainLoginModule required 
 username=\"kafka\" password=\"FRPKl&I!JjvWtkx0\";"'
`
exception is 
`org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:823) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:665) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:646) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:626) ~[kafka-clients-2.8.1.jar:?]
        at zipkin2.collector.kafka.KafkaCollectorWorker.run(KafkaCollectorWorker.java:69) ~[zipkin-collector-kafka-2.23.16.jar:?]
        at zipkin2.collector.kafka.KafkaCollector$LazyKafkaWorkers.lambda$guardFailures$0(KafkaCollector.java:265) ~[zipkin-collector-kafka-2.23.16.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:?]
        at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.IllegalArgumentException: Login module control flag not specified in JAAS config
        at org.apache.kafka.common.security.JaasConfig.parseAppConfigurationEntry(JaasConfig.java:110) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.common.security.JaasConfig.<init>(JaasConfig.java:63) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.common.security.JaasContext.load(JaasContext.java:88) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.common.security.JaasContext.loadClientContext(JaasContext.java:82) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.common.network.ChannelBuilders.create(ChannelBuilders.java:167) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.common.network.ChannelBuilders.clientChannelBuilder(ChannelBuilders.java:81) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.ClientUtils.createChannelBuilder(ClientUtils.java:105) ~[kafka-clients-2.8.1.jar:?]
        at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:737) ~[kafka-clients-2.8.1.jar:?]
        ... 8 more`

**Comment by msillence** [comment]
OK, I've tried the standard jar file in a container with the following yaml file:

```
armeria:
  ports:
    - port: 8888
      ip: 0.0.0.0
      protocol: HTTP

zipkin:
  collector:
    # percentage to traces to retain
    sample-rate: 1.0
    kafka:
      enabled: true
      # Kafka bootstrap broker list, comma-separated host:port values. Setting this activates the
      # Kafka 0.10+ collector.
      bootstrap-servers: xxx.confluent.cloud:9092
      # Name of topic to poll for spans
      topic: zipkin
      # Consumer group this process is consuming on behalf of.
      group-id: zipkin-server
      overrides:
        sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<user>" password="<pass>";
        sasl.mechanism: PLAIN
        security.protocol: SASL_SSL
        ssl.endpoint.identification.algorithm: https
  logging:
    pattern:
      level: "%clr{%5p} %clr{[%X{traceId}/%X{spanId}]}{yellow}"
    level:
      zipkin2: DEBUG
      org.apache.kafka: DEBUG
```

that works fine.

I've tried the same file in the standard docker image (over writing the file /zipkin/BOOT-INF/classes/zipkin-server-shared.yml
and it fails in the orignal way, with the missing class

are you using a stripped down java runtime image that's missing the security module?

I couldn't work out how to use a properties file dropping an application.properties into /zipkin/BOOT-INF/classes didn't seem to have any descerable effect - I couldn't find any documentation on it either, I'm sure I'm missing something obvious here. I'm also assuming that the yaml translates to the following properties:

```
zipkin.collector.kafka.enabled: true
zipkin.collector.kafka.bootstrap-servers: xxx.confluent.cloud:9092
zipkin.collector.kafka.topic: zipkin
zipkin.collector.kafka.group-id: zipkin-server
zipkin.collector.kafka.overrides.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="<user>" password="<password>";
zipkin.collector.kafka.overrides.sasl.mechanism: PLAIN
zipkin.collector.kafka.overrides.security.protocol: SASL_SSL
zipkin.collector.kafka.overrides.ssl.endpoint.identification.algorithm: https
```
