### ISSUE TITLE
can not find servces on Zipkin Server

### ISSUE THREAD

**Issue by Ayue2229** [openzipkin/zipkin#3436]
I couldn't find services on Zipkin, Here are my springboot project config file, and pom denpendency:
```
spring:
    application:
        name: springboot-wy
    zipkin.base-url: http://localhost:9411/
    sleuth.sampler.probability: 1.0
```

```
 <dependency>
     <groupId>org.springframework.cloud</groupId>
     <artifactId>spring-cloud-starter-zipkin</artifactId>
     <version>2.0.0.RELEASE</version>
 </dependency>
```

the zipkin server runs well, and the project log was like :
```
2022-03-16 19:08:16.155  INFO [springboot-wy,fa581971f82f11e4,fa581971f82f11e4,true] 15876 --- [io-8089-exec-10] c.e.d.controller.JerseyHelloController   : hello==============
2022-03-16 19:08:16.396  INFO [springboot-wy,33cca1964589dcf4,33cca1964589dcf4,true] 15876 --- [nio-8089-exec-8] c.e.d.controller.JerseyHelloController   : hello==============
```
