### ISSUE TITLE
Multiple docker-compose environment variable do not work

### ISSUE THREAD

**Issue by mikymigs** [openzipkin/zipkin#3508]
I'm trying to figure out what the options described in [the documentation](https://github.com/openzipkin/zipkin/tree/master/zipkin-server#ui) to configure the UI actually do. It's hard to know because it doesn't seem to be documented except for a vague description in the table. Please let me know if a more detailed documentation exists, for example, is there any screenshot somewhere showing what is the expected display when setting the property "zipkin.ui.environment"?

I'm asking this because I've been trying properties that seem to have no effect but I'm not 100% sure since it might just be a poor understanding on my side of how it's supposed to work.

Here's my docker-compose configuration for Zipkin:
```
  zipkin:
    image: openzipkin/zipkin:2.24.0
    ports:
      - "9411:9411"
    environment:
      ZIPKIN_UI_ENVIRONMENT: "test"
      ZIPKIN_UI_SEARCH-ENABLED: "false"
      ZIPKIN_UI_DEPENDENCY_ENABLED: "false"
      ZIPKIN_UI_SUPPORT-URL: "http://yahoo.com"
```

- ZIPKIN_UI_ENVIRONMENT --> no visible effect on the UI. "test" does not appear anywhere.
- ZIPKIN_UI_SEARCH-ENABLED --> switching between "false" and "true" values does not seem to have any effect on the UI.
- ZIPKIN_UI_DEPENDENCY_ENABLED --> seems to work (it shows/hides the dependencies menu if you clear the cache).
- ZIPKIN_UI_SUPPORT-URL --> seems to work (adds a question mark button à top right corner pointing to the configured link)

So it seems at least the 2 first properties have no effect. Or maybe I just don't understand how they work. Any help is appreciated.

Thank you,
