### ISSUE TITLE
Zipkin Dedendencies for Cassandra

### ISSUE THREAD

**Issue by trcoelho** [openzipkin/zipkin#3509]
Hello!

Am starting using Zipkin and I guess I`ve found a bug where dependencies are not properly displayed when using Apache Cassandra but it does work when I use MySQL or  memory storage as follows:

MySQL or Memory Storage:

docker-compose.yml:
```
services:       
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    expose:
      - 9411
    ports:
      - 9411:9411
    environment:      
      - QUERY_PORT=9411            
      - JAVA_OPTS=-Xms8g -Xmx8g
```
Screenshot:
![image](https://user-images.githubusercontent.com/57268737/218557932-c71a5959-7b0b-4f36-a29d-3bece7ab9325.png)

Cassandra:
docker-compose.yml
```
services:       
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    expose:
      - 9411
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_CONTACT_POINTS=localhost:9042
      - ZIPKIN_UI_DEPENDENCY_ENABLED=true
      - QUERY_PORT=9411            
      - JAVA_OPTS=-Xms8g -Xmx8g
  cassandra:
    container_name: cassandra
    image: cassandra:3.11.14
    expose:
      - 9042
    ports:
      - 9042:9042
```
Screenshot:
![image](https://user-images.githubusercontent.com/57268737/218558606-fe72d9c5-d2d2-4153-a20b-86bf76019dd9.png)

All services POSTs are working fine and we can check them on "Find a trace" user interface. 

I also have tried for environment property `ZIPKIN_UI_DEPENDENCY_ENABLED=true` but still no success.

Could find anything on Zipkin documentation.

Is this a known bug or did I missing some additional configuration.

Thanks in advance.

**Comment by basvanbeek** [comment]
For dependencies to show up you need to run the zipkin-dependencies process at a regular interval. 

See: https://github.com/openzipkin/zipkin-dependencies

**Comment by trcoelho** [comment]
Hi @basvanbeek !
Worked charming!

This is my docker-compose.yml for whom have same query:

```
services:       
  zipkin:
    container_name: zipkin
    image: openzipkin/zipkin
    expose:
      - 9411
    ports:
      - 9411:9411
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_CONTACT_POINTS=localhost:9042
      - ZIPKIN_UI_DEPENDENCY_ENABLED=true
      - QUERY_PORT=9411            
      - JAVA_OPTS=-Xms8g -Xmx8g    
  zipkin-dependencies:
    container_name: zipkin-dependencies
    image: openzipkin/zipkin-dependencies
    environment:
      - STORAGE_TYPE=cassandra3
      - CASSANDRA_CONTACT_POINTS=localhost:9042    
  cassandra:
    container_name: cassandra
    image: cassandra:3.11.14
    expose:
      - 9042
    ports:
      - 9042:9042
```

Thank you for quick response and support!
