### ISSUE TITLE
End-to-End example of Zipkin with mysql

### ISSUE THREAD

**Issue by codefromthecrypt** [openzipkin/zipkin#687]
Zipkin currently has baked configs for file-based SQL, redis and cassandra. @jfeltesse-mdso mentions MySQL is an extremely popular storage backend and would be a great alternative for those getting started with Zipkin and I completely agree.

I suspect this won't be too much effort, as anorm already "supports" it, at least including canning scala files for collector and query and making the url settable.

**Comment by codefromthecrypt** [comment]
Here's a start. I managed to get it working locally today and updated this: https://github.com/openzipkin/zipkin/tree/master/zipkin-anormdb

``` bash
$ mysql -uroot -e "create database if not exists zipkin"
$ MYSQL_USER=root ./bin/collector mysql
$ MYSQL_USER=root ./bin/query mysql
$ ./bin/tracegen
...
```

**Comment by jfeltesse-mdsol** [comment]
awesome! :100:

**Comment by codefromthecrypt** [comment]
PS here's a working docker-compose pointing to amazon RDS. cc @abesto

``` yaml
collector:
  image: quay.io/openzipkin/zipkin-collector:1.7.1
  environment:
    - MYSQL_HOST=zipkin.lalalalalalala.us-west-2.rds.amazonaws.com
    - MYSQL_USER=zipkin
    - MYSQL_PASS=NOT_TELLING
  entrypoint: /bin/sh
  command: -c "java -cp ${ANORMPATCH_CLASSPATH}:/zipkin/zipkin-collector.jar com.twitter.zipkin.collector.Main -f /collector-mysql.scala"
  expose:
    - 9410
  ports:
    - 9410:9410
    - 9900:9900
query:
  image: quay.io/openzipkin/zipkin-query:1.7.1
  environment:
    - MYSQL_HOST=zipkin.lalalalalalala.us-west-2.rds.amazonaws.com
    - MYSQL_USER=zipkin
    - MYSQL_PASS=NOT_TELLING
  entrypoint: /bin/sh
  command: -c "java -cp ${ANORMPATCH_CLASSPATH}:/zipkin/zipkin-query.jar com.twitter.zipkin.query.Main -f /query-mysql.scala"
  expose:
    - 9411
  ports:
    - 9411:9411
    - 9901:9901
web:
  image: quay.io/openzipkin/zipkin-web:1.7.1
  links:
    - query
  ports:
    - 8080:8080
    - 9990:9990
```
